### ISSUE TITLE
AndroidThreeTen.init() Is it required to call in latest version 1.6.8

### ISSUE THREAD

**Issue by rahul-kumawat-vts** [ThreeTen/threetenbp#189]
Are we need to call AndroidThreeTen.init() in latest version of library (1.6.8). Can you please provide change doc.

**Comment by JakeWharton** [comment]
Seems like you want https://github.com/JakeWharton/ThreeTenABP. You'll find a change log there as well.

**Comment by rahul-kumawat-vts** [comment]
I have updated from 'com.jakewharton.threetenabp:threetenabp:1.2.4' to  'org.threeten:threetenbp:1.6.8'. So now are we need to initialise in Application onCrate.

**Comment by rahul-kumawat-vts** [comment]
@JakeWharton Can you please confirm - https://github.com/ThreeTen/threetenbp/issues/189#issuecomment-1944082837

Didn't found the change in any official document.

**Comment by JakeWharton** [comment]
If you are migrating away from ThreeTenABP to ThreeTenBP then you do not need to do anything to initialize the timezone database. It will be read from the jar resources automatically.

I would also suggest profiling your startup after such a change. You should consider a custom timezone database loader that is perhaps lazy or eagerly done on a background thread during splash screen animation because there will likely be non-trivial impact.

**Comment by jodastephen** [comment]
Closing as discussion better suited to ThreeTenABP
