### ISSUE TITLE
ZonedDateTime toString is broken after deserialization

### ISSUE THREAD

**Issue by esneider** [ThreeTen/threetenbp#42]
ZonedDateTime serialization relies in the serialization of ZoneOffset. However, ZoneOffset has a transient id field that is not handled correctly: when deserializing a ZoneOffset, only the totalSeconds field is recovered. The id will be null and the toString method will return "null".

**Comment by jodastephen** [comment]
`ZoneOffset` serialization works fine, because it delegates the work to a serialization proxy (`org.threeten.bp.Ser`). The `readResolve` method on `ZoneOffset` emphasises this by throwing an exception. There are also tests for serialization of `ZoneOffset`.

I suspect you are using a tool that does not correctly implement the serialization specification, which isn't something I can help with.
