### ISSUE TITLE
Inconsistent behaviour with ChronoField.MONTH_OF_YEAR parsing

### ISSUE THREAD

**Issue by cgendreau** [ThreeTen/threetenbp#49]
The following code will not throw a `DateTimeParseException` in the .parse(String) method:
```java
  @Test
  public void testISOOptionalMonthOfYear(){
    DateTimeFormatter isoOptionalDayOfMonthFormatter =
            new DateTimeFormatterBuilder()
                    .appendValue(ChronoField.YEAR, 4, 4, SignStyle.NEVER)
                    .optionalStart()
                    .appendLiteral('-')
                    .appendValue(ChronoField.MONTH_OF_YEAR, 1, 2, SignStyle.NEVER)
                    .optionalEnd()
                    .toFormatter().withResolverStyle(ResolverStyle.STRICT);
    TemporalAccessor ta = isoOptionalDayOfMonthFormatter.parse("2016-40");
  }
```
But, the following code will throw a `DateTimeParseException` in the .parse(String) method:
```java
  @Test
  public void testISOOptionalDayOfMonth(){
    DateTimeFormatter isoOptionalDayOfMonthFormatter =
            new DateTimeFormatterBuilder()
                    .appendValue(ChronoField.YEAR, 4, 4, SignStyle.NEVER)
                    .appendLiteral('-')
                    .appendValue(ChronoField.MONTH_OF_YEAR, 1, 2, SignStyle.NEVER)
                    .optionalStart()
                    .appendLiteral('-')
                    .appendValue(ChronoField.DAY_OF_MONTH, 1, 2, SignStyle.NEVER)
                    .optionalEnd()
                    .toFormatter().withResolverStyle(ResolverStyle.STRICT);
    TemporalAccessor ta = isoOptionalDayOfMonthFormatter.parse("2016-10-40");
  }
```
Seems strange to me, I was expecting the first test to also throw a  `DateTimeParseException` instead of returning a `DateTimeBuilder[fields={Year=2016, MonthOfYear=40}, ISO, null, null, null]`.

**Comment by jodastephen** [comment]
The behaviour matches that of the JDK, so no change will be made to the backport code.

This difference occurs because the first test does not contain enough information for form a date. Parsing has two parts - raw parsing and resolving. The resolve step will take time fields and merge them to form a `LocalTime`, and the date fields and merge them to form a `LocalDate`. Since there are not enough fields to create a date in the first test, the raw parsed data is left as-is.

The invalid input would be caught if you used `parseDefaulting(ChronoField.DAY_OF_MONTH, 1)` in the formatter. Or if you call `YearMonth.of(ta)` once parsed.
